### ISSUE TITLE
ZooCompareDb fails on simple databases.

### ISSUE THREAD

**Issue by slavap** [tzaeschke/zoodb#101]
Test case attached, rename png to zip.
Also please make field ZooCompareDb.logToConsole public.

![zoodbbugs3](https://cloud.githubusercontent.com/assets/4129763/26473526/c484278c-4160-11e7-9d00-c967c8f5a26e.png)

**Comment by tzaeschke** [comment]
Reproducible. Tested in Test_015_DatabaseComparison.
Again, this qualifies for the bounty.
