### ISSUE TITLE
PersistenceManagerFactory getPersistenceManager() hangs up in case there is active transaction.

### ISSUE THREAD

**Issue by slavap** [tzaeschke/zoodb#105]
See adopted Datanucleus concurrency test:
https://github.com/tzaeschke/zoodb/pull/102/commits/1d122bffbe909306afc3a34567e50fe0f3196e6b

This code hangs up:
```java
            tx.begin();
            LinkedList<Thread> threads = new LinkedList<>();
            Extent<Transfer> ext = pm.getExtent(Transfer.class, true);
            Iterator<Transfer> iter = ext.iterator();
            while (iter.hasNext()) {
                Transfer t = iter.next();
                threads.add(startConcurrentTransfer(JDOHelper.getObjectId(t)));
            }
            tx.commit();
```
because there is a call of getPersistenceManager() in startConcurrentTransfer()
So code should be changed like this to work properly:
```java
            tx.begin();
            LinkedList<Thread> threads = new LinkedList<>();
            List<Object> objIds = new ArrayList<>();
            Extent<Transfer> ext = pm.getExtent(Transfer.class, true);
            Iterator<Transfer> iter = ext.iterator();
            while (iter.hasNext()) {
                Transfer t = iter.next();
                //threads.add(startConcurrentTransfer(JDOHelper.getObjectId(t)));
                objIds.add(JDOHelper.getObjectId(t));
            }
            tx.commit();
            for (Object id : objIds) threads.add(startConcurrentTransfer(id));
```

**Comment by tzaeschke** [comment]
Thanks a lot. I'm a bit busy at the moment, I'll have a look next week.

**Comment by tzaeschke** [comment]
Hi, if I understand correctly, this is a fix for the test that you provided.
Or are you seeing a problem with ZooDB? If yes, could you describe the error and tell me which branch you tested? At the moment the test runs just fine for me.

**Comment by slavap** [comment]
Hi,
No, it's not a fix for the test.
If you change code to the first version, test won't work, and just hangs up.
The second version (currently in the code) works just fine, that's why test works for you.
Both versions are semantically equal of course.
I'm using master branch, let me know if you need additional info.

**Comment by tzaeschke** [comment]
The problem is that ZooDB currently uses one write-lock to lock the whole server. That means that there can be only one open transaction at any time. I had the same problem in some of the Concurrent-Schema tests. As a workaround, I implemented a function `DiskAccessOneFile.allowReadConcurrency(true);` (place it before `tx.begin()`). This causes the server to use only a read-lock, but it is not threadsafe and should only be used if no more than one thread is controlling the different transactions.
Thanks for reporting this and for the fix to the concurrency test.

**Comment by tzaeschke** [comment]
Fixed. In ConcurrencyTest I had to change the `startConcurrentTransfer` method to deal with OptimisticVerification Exceptions:
```
           public void run()
            {
                LOG.debug(">> Starting thread " + transferId + " in pm=" + pm);
                synchronized (lock)
                {
                    lock.notifyAll();
                }

                boolean success = false;
                do {
	                try {
	                    pm.currentTransaction().begin();
	                    Transfer t = (Transfer) pm.getObjectById(transferId, true);
	                	performTransfer(t);
	                	success = true;
	                } catch (JDOOptimisticVerificationException e) {
	                	success = false;
	                	System.out.println("Transaction failed, retrying...");
	                } finally {
	                	if (success) {
	                        closePm(pm);
	                	}
	                }
                } while (!success);
                LOG.debug(">> Completed thread " + transferId + " in pm=" + pm);
            }
```
