### ISSUE TITLE
Query.setOrdering throws java.lang.NullPointerException if the DB is empty

### ISSUE THREAD

**Issue by pstoop** [tzaeschke/zoodb#96]
If the DB contains no objects of a certain class (ex Book) and
one does a query for that class, it works as expected and returns
an empty Collection of Books.

However if one calls setOrdering on that query, setOrdering throws
java.lang.NullPointerException.

Example Code:
[Book.txt](https://github.com/tzaeschke/zoodb/files/852750/Book.txt)

There is also a chance that there are similar bugs.

**Comment by tzaeschke** [comment]
Thanks a lot for the report. I'm quite busy at the moment but I will 
process it later this week.

Cheers,
Tilmann
