### ISSUE TITLE
ZooPC should not be required to be super class of all persistent classes.

### ISSUE THREAD

**Issue by slavap** [tzaeschke/zoodb#97]
Often it's just not possible to inherit persistent class from ZooPC. And ideally it should be possible to use POJO as persistent class.
The simplest way to achieve that is adding targetObj concept to ZooPC class, which means that everywhere zooPCobj.getClass() called, it should be replaced by zooPCobj.getTarget().getClass() and then createSchema() for example will process "real" data object. I.e. it should be possible for ZooPC to be a "holder" of real data classes in my application. 
Perhaps there is a better way how to eliminate inheritance from ZooPC requirement for persistent classes.

**Comment by tzaeschke** [comment]
Using POJOs will be mostly possible one the bytecode enhance is in place. It will automatically insert ZooPC as superclass. Potentially, it could (potentially) even be inserted between a class that is meant be be persistent and its non-persistent superclass (if any exists).

I'm not quite sure what you mean by the target-object concept, but the ZooPC serves several purposes: Reference to schema, POJO state (clean, dirty, new, hollow, ...), and the object ID (OID). 

The reason for using a persistent super-class is mostly performance. Having a separate State object for each POJO, along with a HashMap to look up the State object can easily double the required amount of objects in memory. Using State object may also lead to numerous additional HashMap calls to get the State object for a given POJO. Unfortunately, HashMap lookups are not as cheap, the commonly assumed O(1) doesn't really hold once you take memory transfer into account.

For the future, once the bytecode enhance is implemented, there are several options. One would be to insert ZooPC only as direct superclass of persistent objects. Alternatively, one could simply implement an interface and directly insert the missing fileds of state,OID, ... into a given class.
This could still pose problems when classes are serialized and send from/to a peer that has no such extends classes. But I can't see a solution where that fits all requirements...

May I ask what your use case is where using ZooPC as superclass is not possible?

**Comment by slavap** [comment]
My use case is the following: there are domain objects, and there is serialization/storage layer. Storage layer is interface with multiple different implementations. I wanted to add zoodb as additional implementation, but I cannot change inheritance chain of domain classes and add additional storage specific code to their getters/setters. Bytecode enhancer sounds as possible solution to me, I thought about it by myself. 
P.S. Also I've found a bug in zoodb's arrays serialization, will open issue next Monday.

**Comment by tzaeschke** [comment]
Thanks. I thought about this a bit more, and I believe this should actually work with the byte-code enhance (which will _not_ appear anytime soon unfortunately). Serialization should be either hardcoded in special methods, in this case it is easy to skip ZooDB fields. Otherwise it may rely on reflection to find all fields to serialize, this should also work because, having control of the ClassLoader, I should be able to manipulate reflection to _not_ return any ZooDB fields.

**Comment by mojo2012** [comment]
What's the plan on implementing such a byte code enhancer?

**Comment by tzaeschke** [comment]
In terms of timeline? After some more clean-up, I have first some work on the query parser on the list. After that it's going to be either the code enhancer or refactoring the current schema evolution, it's a bit broken. I suppose that means I'll work on that beginning of next year, with some luck already end of this year.

Why are you asking?

**Comment by mojo2012** [comment]
I am currently building a RAD framework for building microservices (based on my experience with SAP Hybris). Currently I have a custom persistence layer based on MapDB (not yet fully working).
First this was actually just for fun and there’s still a lot to do.

To save some time I am evaluating some frameworks like datanucleus, hibernate etc. They dont need to modify my domain models, except for some annotations.

It would be nice if zoodb was kinda compatible with standard JDO annotations.

**Comment by tzaeschke** [comment]
Well, I definitely plan to support JDO annotations and bytecode enhancement. But you may have to wait a bit before it is available. 
Unless someone else finds some time to implement it before that :-)

**Comment by mojo2012** [comment]
Hey I just wrote an classfiletransformer used by a load-time-weaver for my own project. Works pretty well. It parses my own annotations and injects JPA annotations before the entities are processed by hibernate.

Take a look at this: https://github.com/mojo2012/spot-framework/blob/develop/spot-core/src/main/java/at/spot/core/persistence/instrumentation/transformers/JpaEntityClassTransformer.java

The used LTW framework can be found here: https://github.com/mojo2012/spot-instrumentation. It's a fork of invesdwin-instrument (can be found on github too).

It basically injects a java agent that registers classfiletransformers.

This could easily be transformed into a maven mojo, that does this weaving magic after compilation.
I will probabely create such a mojo in the near future.

**Comment by tzaeschke** [comment]
@mojo2012 I think as a first step I would simply use a modified ClassLoader that modifies the classes on the fly while loaded, there would be no need to rewrite the class files. I also should probably stick to the JDO way of injecting the ClassLoader, I would have to check how that works. Anyway, thanks, the framework may come handy once I get there :-)

**Comment by mojo2012** [comment]
The class modifications are not stored! This is actually a modification before the class is loaded (load time weaving). 
You can of course do this directly in a custom classloader, but it should be done using JVM instrumentation (aka the way I went for)
With custom classloaders you can never be sure, if the class has already been loaded by another classloader. But if you want to go in that direction, checkout org.springframework.boot.devtools.restart.classloader.RestartClassLoader and the spring-boot-devtools.

**Comment by tzaeschke** [comment]
Well, I looked at your link: JpaEntityClassFileTransformer I didn't look to closely, but at first sight, lines 116-122 looked a lot like it's writing a class file...
Anyhow, I wasn't aware that independent ClassLoaders can block each other from modifying classes, isn't that kind of the point of having ClassLoaders? 
And yes, I should definitely look at instrumentation a bit more, it sounds like it is more powerful than I thought. Last time I really looked at this topic (several years ago, Java 5?), ClassLoaders were the way to go.

**Comment by mojo2012** [comment]
I'm writing the classes to disk just for debugging purpose - to be able to inspect my modifications.
This is not necessary at all. The transformer modifies the classes before they are handed over to the actual classloader.

**Comment by mojo2012** [comment]
I wrote another small classtransformer that injects the *"zooActivate*"* calls.
https://github.com/mojo2012/spot-framework/blob/1dbfd50ff45c59c64e43cb4cdca2eb37b317e792/spot-core-model-infrastructure/src/main/java/at/spot/core/persistence/instrumentation/transformers/ZooDbEntityClassTransformer.java
